"""September 24 supply-delay plan and narrowly scoped notices on reference lessons."""
import re

STUDENT = 'september-24-backup.html'
MENTOR = 'mentor-backup-plan.html'
AGENDA = [
    ('8:00–8:20', 'Welcome, user/need prompt, demonstrations, roles, and equipment expectations.'),
    ('8:20–9:25', 'Wearables: one-LED felt circuit. Robotics: connect, identify the sensor, and explore outputs.'),
    ('9:25–9:38', 'Snack; leave all circuits powered off and return needles before leaving.'),
    ('9:38–9:42', 'Return, settle, and check the assigned kits.'),
    ('9:42–10:05', 'Wearables: finish, inspect, and test the circuit. Robotics: combine an input and two outputs.'),
    ('10:05–11:09', 'Wearables: micro:bit blocks, download, personalize, and test. Robotics: three trials, one change, and retest.'),
    ('11:09–11:17', 'Save evidence, return needles, power off, and take a short reset break.'),
    ('11:17–11:45', 'Cross-group demonstrations (8 min), paper future symbol (10 min), and observed NeoPixel preview (10 min).'),
    ('11:45–12:42', 'Three distinct ideas, selection, and labeled project sketches.'),
    ('12:42–1:12', 'Lunch.'),
    ('1:12–1:16', 'Return and settle.'),
    ('1:16–2:00', 'Proposal studio and staggered mentor conferences; waiting students complete diagrams and first-test plans.'),
    ('2:00–2:21', 'Table pitches, revisions, mentor decisions, and the next action.'),
    ('2:21–2:41', 'Save/upload evidence, count equipment, power off, label storage, and clean up.'),
]


def agenda():
    rows = ''.join(f'<tr><th scope="row">{time}</th><td>{task}</td></tr>' for time, task in AGENDA)
    return '<div class="prep-table-wrap" tabindex="0" role="region" aria-label="Thursday agenda"><table class="prep-table"><thead><tr><th scope="col">Time</th><th scope="col">Activity</th></tr></thead><tbody>' + rows + '</tbody></table></div>'


def without_backup_notices(source):
    return re.sub(r'<!-- september-backup:start -->.*?<!-- september-backup:end -->', '', source, flags=re.S)


def notice(mentor=False):
    href = MENTOR if mentor else STUDENT
    return ('<!-- september-backup:start --><aside class="section compact" aria-label="September 24 plan update">'
            '<div class="callout teal"><strong>September 24 · Backup plan is active.</strong> '
            'Use sewn LED practice, micro:bit coding, and Hummingbird Bit activities. Future Stamp becomes a paper symbol; '
            'NeoPixels are an observed video/diagram preview. Record wood stitching and physical NeoPixel testing as deferred. '
            f'<a href="{href}">Open today’s agenda and adjusted evidence requirements →</a> '
            'The original lesson below remains a reference; today’s plan takes priority.</div></aside><!-- september-backup:end -->')


def sync_notices(root):
    names = ['start-here.html', 'wearable-technology.html', 'creative-robotics.html',
             'stamp-from-the-future.html', 'sewable-led-basics.html', 'conductive-thread-basics.html',
             'meet-the-microbit.html', 'meet-the-neopixels.html', 'meet-the-hummingbird.html',
             'wearable-design-proposal.html', 'robotics-design-proposal.html', 'canvas-checkpoint-1.html',
             'mentor-approval.html', 'mentor-lesson-plans.html', 'mentor-print-center.html',
             'mentor-station-checklist.html', 'mentor-future-stamp-prep.html', 'mentor-circuit-lab-prep.html',
             'mentor-neopixel-prep.html', 'mentor-hummingbird-prep.html']
    for name in names:
        path = root / name
        source = without_backup_notices(path.read_text(encoding='utf-8'))
        source = re.sub(r'(<main\b[^>]*>)', lambda m: m[1] + notice(name.startswith('mentor-')), source, count=1)
        # Anchor links to these long reference pages must land on the active-plan notice too.
        if name == 'mentor-lesson-plans.html':
            source = source.replace('id="day-1">', 'id="day-1">' + notice(True), 1)
            source = source.replace('id="day1-tech-rotations">', 'id="day1-tech-rotations">' + notice(True), 1)
        if name == 'mentor-print-center.html':
            source = source.replace('id="september-24">', 'id="september-24">' + notice(True), 1)
        path.write_text(source, encoding='utf-8', newline='\n')


def page(document, filename, title, body):
    result = document(filename, title, body)
    result = result.replace('</head>', '<link rel="stylesheet" href="assets/neopixel-prep.css"><link rel="stylesheet" href="assets/mentor-prep.css"><link rel="stylesheet" href="assets/backup-plan.css"></head>')
    return result.replace('<body>', '<body class="mentor-prep backup-plan">')


def build_pages(root, document):
    student = '''
<section class="page-hero prep-hero"><p class="eyebrow">Thursday, September 24, 2026 · Active backup plan</p>
<h1>Code, test, and<br><span>design the future.</span></h1>
<p class="lede">Use the supplies already in Room 14. Make something respond, learn from a test, and turn that discovery into a project idea.</p>
<p><strong>8:00 a.m.–2:41 p.m. · Snack 9:25–9:38 · Lunch 12:42–1:12</strong></p>
<nav class="prep-jumps no-print" aria-label="On this page"><a href="#wearables">Wearables</a><a href="#robotics">Robotics</a><a href="#preview">Paper &amp; preview</a><a href="#evidence">Save evidence</a><a href="#agenda">Agenda</a></nav></section>
<section class="section compact"><div class="callout teal"><strong>Today’s route:</strong> two supervised groups, followed by shared design time. Wearables practice in pairs and create individual proposals. Robotics stay in their project pairs. The October 13 badge event is a separate activity.</div></section>
<section class="section compact" id="wearables"><p class="eyebrow">Jennifer · W1–W3 · 18 students</p><h2>Sew a circuit. Program a response.</h2>
<div class="guide-grid"><article class="guide-card"><h3>1. One-LED felt practice</h3><ol><li>Trace the positive and negative paths on your mentor’s working example.</li><li>Practice sewing a pad connection. Share the circuit parts; both partners take a turn.</li><li>Sew separate paths with the battery removed. Ask for an inspection before power is installed.</li><li>Test, explain what happened, and save a labeled photo. A useful in-progress sample counts.</li></ol><p><a href="sewable-led-basics.html">LED lesson</a> · <a href="conductive-thread-basics.html">Stitching lesson</a></p></article>
<article class="guide-card"><h3>2. A helpful micro:bit interface</h3><ol><li>Use your W-labeled board and laptop. Start with A → heart, B → happy face, A+B → clear.</li><li>Switch the keyboard role so each partner downloads and tests.</li><li>Change the symbols for a real user: ready/help, welcome/wait, or two useful messages.</li><li>Try A, B, and A+B three times. Improve one thing and retest. Save code and a screenshot.</li></ol><p><a href="mentor-microbit-prep.html#starter">Open the blocks and text starter</a> · <a href="meet-the-microbit.html">Student micro:bit lesson</a></p></article></div>
<p>Your shirt-and-hat proposal is individual, even when practice equipment is shared. The felt circuit is a skill sample for your shirt; micro:bit coding prepares you for your programmable hat.</p></section>
<section class="section compact" id="robotics"><p class="eyebrow">Stephanie · R1–R3 · Nine pairs</p><h2>Make an invention respond.</h2>
<ol class="guide-steps"><li><strong>Connect and identify.</strong> Use your assigned R-labeled Hummingbird Bit and iPad. Record the kit name, input, ports, and reset.</li><li><strong>Explore a change.</strong> Measure two conditions with the mentor-selected sensor. Explain how the reading changes. Use only the threshold and setup tested for your kit.</li><li><strong>Build an interaction.</strong> Program one input to change two outputs. Use LEDs and a securely mounted position servo when released by your mentor; the fallback uses two kit LEDs.</li><li><strong>Test and improve.</strong> Predict a response, run three trials, change one thing, and retest. Swap Driver/Navigator after each challenge. Explain the ready state and how to reset.</li></ol>
<p>Two LEDs are two outputs of the same type. If movement is deferred, record that accurately and identify any later mechanism test your proposal needs.</p>
<p><a href="meet-the-hummingbird.html">Hummingbird student lesson</a> · <a href="mentor-hummingbird-prep.html#starter">Mentor-approved starter recipes</a></p></section>
<section class="section compact" id="preview"><h2>A paper symbol and an observed light pattern</h2><div class="guide-grid">
<article class="guide-card"><h3>Future symbol · 10 minutes</h3><p>Draw a small symbol for a future person, community, or need on a paper grid or plain paper. Add two colors and explain what they mean. Save the drawing with the caption <strong>“Paper symbol design; wood stitching deferred.”</strong> A digital drawing also works.</p></article>
<article class="guide-card"><h3>NeoPixel preview · 10 minutes</h3><p>Watch the mentor’s selected video or examine an illustrated example. Sketch a color sequence for your hat and say what button A, button B, and A+B off should do. Label the evidence <strong>“Observed video/diagram; physical NeoPixel test deferred.”</strong></p><p><a href="mentor-backup-plan.html#preview">Open the preview resources</a></p></article></div></section>
<section class="section compact" id="evidence"><h2>What to save today</h2><div class="guide-grid"><article class="guide-card"><h3>Each Wearables student</h3><ul><li>Paper symbol and meaning.</li><li>Circuit practice photo with your own observation and contribution.</li><li>micro:bit program screenshot and a physical test note, or a clearly labeled simulator result.</li><li>Observed NeoPixel pattern with the physical test marked deferred.</li><li>Three distinct ideas; individual shirt front/back and hat sketches; circuit/power placement, button effects, removable electronics idea, and first prototype question.</li></ul><p><a href="wearable-design-proposal.html">Complete the Wearables proposal</a> · <a href="output/pdf/September-24-Backup-Wearables-Studio-Sheets.pdf">Backup student sheets</a></p></article>
<article class="guide-card"><h3>Each Robotics pair</h3><ul><li>Kit/input/output identification and reset note.</li><li>Three-trial record, one change, and a retest.</li><li>Saved program and a photo of the actual setup.</li><li>Three distinct ideas; selected user/need, labeled physical concept, one input, two outputs, input → decision → output storyboard, partner roles, and first prototype question.</li></ul><p><a href="robotics-design-proposal.html">Complete the Robotics proposal</a> · <a href="output/pdf/September-24-Backup-Robotics-Team-Studio-Sheets.pdf">Backup team sheets</a></p></article></div>
<div class="callout"><strong>September 24 evidence adjustment:</strong> today’s substitutions fulfill the paper/observation portions of this workday. They do not certify wood stitching, a sewn circuit you have not powered, or physical NeoPixel operation. Save what you actually did. Your mentor records Approved, Revise and Return, or Needs Technical Review; unresolved hardware tests remain named next actions.</div>
<p><a href="canvas-checkpoint-1.html">Open Canvas submission directions</a>. If upload is unavailable, save named files locally and give the mentor the storage location before leaving; record upload as pending. No homework is added.</p></section>
<section class="section compact" id="agenda"><h2>Thursday’s agenda</h2>''' + agenda() + '''</section>
<section class="section compact no-print"><div class="button-row"><a class="button" href="mentor-backup-plan.html">Mentor preparation</a><button class="button secondary" data-print type="button">Print today’s guide</button></div></section>'''

    mentor = '''
<section class="page-hero prep-hero"><p class="eyebrow">Active plan · Thursday, September 24, 2026</p><h1>Thursday’s<br><span>backup plan.</span></h1>
<p class="lede">Code, test, and design the future with last year’s supplies. Two supervised groups, meaningful trials, and a reviewed proposal for every project.</p>
<p><strong>Room 14 · 8:00 a.m.–2:41 p.m. · 36 students · Three mentors</strong></p>
<div class="button-row no-print"><button type="button" class="button" data-print>Print this mentor plan</button><a class="button secondary" href="september-24-backup.html">Open the student day guide</a><a class="button secondary" href="#print">What to print</a></div>
<nav class="prep-jumps no-print" aria-label="On this page"><a href="#gather">Gather &amp; test</a><a href="#agenda">Agenda</a><a href="#wearables">Wearables</a><a href="#robotics">Robotics</a><a href="#preview">Paper &amp; preview</a><a href="#review">Review &amp; close</a></nav></section>
<section class="section compact"><div class="callout teal"><strong>Selected after the supply delay.</strong> Tri reported the sewing materials, nine standalone micro:bits with laptops/data cables/battery packs, and nine Hummingbird Bit kits with assigned micro:bits, powered iPads/BirdBlox, LEDs, sensors, and optional servos/mounting supplies. This is an inventory report, not a completed equipment test. Sensor types, exact spare counts, and shared classroom/printing supplies still need a physical check.</div>
<div class="guide-grid"><article class="guide-card"><h3>Jennifer · Wearables</h3><p>18 students at W1–W3. Nine practice pairs share circuits and computers; each student produces her own shirt-and-hat proposal. Lead one activity across the group at a time, collecting needles before coding.</p></article><article class="guide-card"><h3>Stephanie · Robotics</h3><p>18 students at R1–R3 in nine fixed project pairs. Keep each numbered kit and iPad together. Switch Driver/Navigator roles, then review nine team proposals.</p></article></div>
<p><strong>Tri:</strong> prepare and release equipment, support electrical inspections and troubleshooting, run the shared preview, and resolve technical-review questions. These are two teaching groups; six tables do not imply six independently staffed stations.</p></section>
<section class="section compact" id="gather"><h2>Pack complete sets, then test them.</h2>
<div class="prep-table-wrap" tabindex="0" role="region" aria-label="Confirmed inventory and preparation"><table class="prep-table"><thead><tr><th scope="col">Area</th><th scope="col">Prepare from available stock</th><th scope="col">Release check</th></tr></thead><tbody>
<tr><th scope="row">Nine sewing sets</th><td>One compatible sewable holder, coin cell, and LED per pair; conductive thread; two felt practice pieces and two needles. Shared threaders, snips, marker, and counted needle tray. Add a working mentor example and spare if stock allows.</td><td>Record the actual LED/module, battery and holder, polarity, and built-in or required external current limiting. Tri builds and tests the matching sample before any student-powered circuit.</td></tr>
<tr><th scope="row">Nine W coding sets</th><td>W-labeled micro:bit, Windows laptop/charger, tested USB data cable, and matching battery holder/cells.</td><td>Open the saved starter and transfer it. Verify A, B, A+B clear, restart, and unplugged operation. Keep the battery holder disconnected during USB use in this classroom workflow.</td></tr>
<tr><th scope="row">Nine R Robotics sets</th><td>Hummingbird Bit and its R micro:bit, matching power, iPad/BirdBlox/charger, sensor, two wired LEDs, terminal tool and leads. Stage a mounted position servo only if ready.</td><td>Verify identity/Bluetooth, power, sensor type and two readings, output ports, and reset. Test safe motion on the actual mounting before releasing a servo. R boards retain BirdBrain firmware.</td></tr>
<tr><th scope="row">Shared materials</th><td>Paper or digital drawing space, pencils/colors, labels/bags, project storage, display, photo device, student sheets, Canvas access, and locally saved starters.</td><td>Check these classroom items in person. Open the preview media on the school network and have the illustrated fallback ready.</td></tr>
</tbody></table></div>
<p class="record-lines">Physical release record: W sets ready ____ / 9 · R sets ready ____ / 9 · Sewing sets ready ____ / 9<br>Sensor type / kit IDs ____________________ · Spare / fallback ____________________<br>Tested by / date ____________________ · Missing/failed item and owner ____________________</p>
<p>If the verified sewing circuit is unavailable, teach isolated stitching and label powered testing deferred. If some kits fail, keep pairs intact and rotate hardware turns while waiting pairs storyboard and plan trials. The micro:bit simulator can support coding; label simulator evidence explicitly. Use a whole working spare or observed demonstration for an unresolved Robotics fault.</p>
<p><a href="mentor-circuit-lab-prep.html#gather">Circuit identification and photo references</a> · <a href="mentor-microbit-prep.html#gather">W kit preparation</a> · <a href="mentor-hummingbird-prep.html#gather">R kit preparation</a></p></section>
<section class="section compact" id="agenda"><h2>One full Thursday</h2>''' + agenda() + '''<p>Protect the final 20 minutes. Stop a build at a meaningful in-progress state rather than losing evidence and cleanup time.</p></section>
<section class="section compact" id="wearables"><h2>Wearables · Sew, then code</h2>
<div class="guide-grid"><article class="guide-card"><h3>8:20–10:05 · Circuit Lab</h3><p>88 activity minutes around snack and return time. Aim for a shared one-LED sample; completion depends on the inspected work.</p><ol><li><strong>Demonstrate:</strong> trace the complete loop and separate +/− paths on the working example.</li><li><strong>Practice:</strong> each student makes snug pad loops and a short stitch path on isolated felt.</li><li><strong>Build:</strong> draw the pair’s simple layout and sew with the battery removed. Inspect both sides and trim loose conductive tails.</li><li><strong>Check:</strong> queue for a mentor inspection. Only then install the matching battery and test. Save each student’s contribution and observation.</li><li><strong>Stop:</strong> remove power before repairs. Collect/count needles for snack and at the end. A persistent fault moves to INSPECT; use a complete spare.</li></ol><p>Fast finishers annotate the loop and explain an unpowered fault sample. Students needing more time save their practice and explain the mentor example.</p><p><a href="mentor-circuit-lab-prep.html#prepare">Detailed assembly and test checks</a> · <a href="https://learn.sparkfun.com/tutorials/lilypad-basics-e-sewing">SparkFun illustrated stitching techniques</a></p></article>
<article class="guide-card"><h3>10:05–11:09 · micro:bit blocks</h3><ol><li><strong>10 minutes:</strong> model A → heart, B → happy, A+B → clear. Start/reset with a blank screen.</li><li><strong>20 minutes:</strong> both partners take a download/test turn on the W board using the laptop and data cable.</li><li><strong>15 minutes:</strong> redesign the two symbols for a chosen user. Ask another pair what the symbols communicate.</li><li><strong>19 minutes:</strong> run three A/B/A+B trials, make one change, retest, and save code plus a screenshot.</li></ol><p><a href="mentor-microbit-prep.html#starter">Editable blocks, text code, and transfer guide</a></p><p>Use the working simulator if a download fails and label that result. Never load MakeCode onto an R board to borrow it for this activity.</p></article></div></section>
<section class="section compact" id="robotics"><h2>Robotics · An input, a decision, two outputs</h2>
<p>Use the <a href="mentor-hummingbird-prep.html#starter">existing R1–R4 and SAFE RESET recipes</a> when the prepared distance-sensor/LED/servo setup matches. Sensor availability was confirmed, but the type was not specified: Tri selects and rehearses the matching <a href="https://learn.birdbraintechnologies.com/hummingbirdbit/birdblox/program">official BirdBlox sensor lesson</a> before students begin. Record the actual sensor, ports, units, readings, and comparison direction.</p>
<ol class="guide-steps"><li><strong>8:20–9:25 · First successes.</strong> Match Bluetooth identity, demonstrate stop/reset, read two sensor conditions, and control outputs separately. Record what the input measures. Secure any servo and mark its movement area before use.</li><li><strong>9:42–10:05 · Combine.</strong> Choose a user/need and implement one small response. Use the mentor’s tested threshold and safe positions.</li><li><strong>10:05–11:09 · Test/improve.</strong> Predict the ready and active responses, run three trials, change one parameter or behavior, and repeat the same test. Save the program, setup photo, and reset note. Each partner explains the full system.</li></ol>
<div class="guide-card"><h3>Two-LED fallback when movement is not ready</h3><p>Disconnect unused motion hardware with power off. Use kit LEDs in LEDS 1 and 2; record the input and its tested comparison. Rehearse this finite block recipe before handing it to students:</p><ol><li>On start, set both LEDs to 0.</li><li>If the selected sensor condition is true, set LED 1 to 50 and LED 2 to 0; otherwise set LED 1 to 0 and LED 2 to 50.</li><li>Wait one second, then set both LEDs to 0. Run again for each test condition.</li></ol><p>This has two output devices, both of the same type. Mark motion exploration deferred if no servo was tested. If no sensor is ready, a mentor may prepare a micro:bit-button input using BirdBlox’s Buttons lesson; otherwise record observation and the missing-input test.</p></div>
<p><strong>Normal shutdown:</strong> let the one-shot challenge finish; use the rehearsed SAFE RESET, allow motion to settle, Stop, disconnect, and power off. With the two-LED setup, the reset sets both LEDs to 0. For unexpected motion, heat, odor, or a jam, stop code if possible and power off immediately; keep hands clear and do not command another movement.</p></section>
<section class="section compact" id="preview"><h2>11:17–11:45 · Share, draw, observe</h2><ol class="guide-steps"><li><strong>Eight-minute cross-group share.</strong> Selected pairs demonstrate a circuit/interface and a robot interaction. Everyone records one useful capability.</li><li><strong>Ten-minute paper Future Stamp.</strong> Each student draws a symbol for a future need with a brief color/meaning caption. Use paper or a digital sketch. No wood or decorative-floss stock is required. Record paper design complete and wood stitching deferred.</li><li><strong>Ten-minute NeoPixel preview.</strong> Tri shows a short selected excerpt, then students sketch a hat-light sequence and A/B/A+B-off behavior. Record observed video/diagram and defer the physical strip test.</li></ol>
<div class="guide-grid"><article class="guide-card"><h3>Official preview video</h3><video class="prep-video no-print" controls preload="none"><source src="https://video.microbit.org/support/neopixel.mp4" type="video/mp4">Open the linked video or illustrated guide below.</video><p><a href="https://video.microbit.org/support/neopixel.mp4">Open the micro:bit NeoPixel video</a> · <a href="https://support.microbit.org/support/solutions/articles/19000130206-using-neopixels-with-the-micro-bit">Official illustrated coding example</a></p><p>Use the resource to observe programming and patterns. Its hardware example is not the wiring instruction for our planned hat system.</p></article>
<article class="guide-card"><h3>If media will not play</h3><p>Use the locally available <a href="mentor-neopixel-prep.html#starter">starter blocks and text</a> and <a href="mentor-neopixel-prep.html#wiring">system diagram</a>. Trace which command would change the pixels and which command turns them off. Record “observed diagram/code”; do not claim a running strip or video was seen.</p><p>No student assembles an improvised NeoPixel power harness today. Later physical work uses the prepared, tested system in the mentor guide.</p></article></div></section>
<section class="section compact" id="slides"><h2>Thursday’s revised slide deck</h2><p>Eight slides for September 24: welcome and fixed home tables, the day’s schedule, Wearables and Robotics practice, paper Future Stamp and observed NeoPixel preview, ideas, proposal review, and cleanup.</p><div class="button-row"><a class="button" href="output/pdf/September-24-Backup-Workday-Slides.pdf">Open the projection PDF</a><a class="button secondary" href="outputs/mentor-meeting-decks/September-24-Backup-Workday-Slides.pptx">Download editable PowerPoint</a></div><p><strong>Mentors:</strong> the PowerPoint notes include timing, demonstration cues, tutorial links, and fallback instructions. Videos are linked, not embedded; open the selected tutorials before students arrive. Use this revised deck for Thursday.</p></section>
<section class="section compact" id="table-cards"><h2>Six revised table cards for Thursday</h2><p>Print this six-page PDF once: <strong>single-sided, landscape, one page per sheet</strong>. Place each card flat in a sleeve or on a clipboard at its matching home table.</p><p><a class="button" href="output/pdf/September-24-Backup-Table-Cards.pdf">Open and print all six table cards</a></p><div class="guide-grid"><article class="guide-card"><h3>W1, W2, W3 · Jennifer</h3><p>Six students in three practice pairs per table. Prepare three felt-circuit sets and have three W micro:bit/laptop sets ready for coding. Keep batteries mentor-controlled and needles counted.</p></article><article class="guide-card"><h3>R1, R2, R3 · Stephanie</h3><p>Six students in three Robotics pairs per table. Prepare three numbered Hummingbird Bit kits with their assigned iPads and matching power setups.</p></article></div><p><strong>Fixed home tables:</strong> students stay with their pathway group and follow their mentor through the activities. These cards replace the old station-rotation cards for Thursday. Each includes the activity sequence, safety reminders, and break/cleanup times.</p></section>
<section class="section compact" id="print"><h2>Print the backup student packets.</h2><p><strong>Table cards:</strong> print <a href="output/pdf/September-24-Backup-Table-Cards.pdf">one complete six-page set</a>, single-sided in landscape. See the <a href="#table-cards">simple table setup instructions</a>.</p>
<ul><li><strong>Wearables:</strong> 20 complete sets (18 students + 2 backups) of the <a href="output/pdf/September-24-Backup-Wearables-Studio-Sheets.pdf">four-page backup Wearables studio sheets</a>, duplex as two sheets per student.</li><li><strong>Robotics:</strong> 11 complete sets (9 pairs + 2 backups) of the <a href="output/pdf/September-24-Backup-Robotics-Team-Studio-Sheets.pdf">four-page backup Robotics studio sheets</a>, duplex as two sheets per pair.</li><li><strong>Mentors:</strong> one copy of this active plan per mentor, or one shared printed copy with the others digital. Use one shared <a href="mentor-station-checklist.html">opening/closing checklist</a>; mark wood/NeoPixel hardware deferred. Keep full tutorials digital.</li></ul>
<div class="callout"><strong>Use the packets labeled “September 24 backup.”</strong> The Wearables pages already distinguish paper design, observed NeoPixel patterns, physical micro:bit work, and simulator-only work. The Robotics pages accept the actual sensor conditions and the two-LED fallback, with movement marked tested or deferred. Each packet keeps the three-idea and proposal pages. If the original packets are already printed, write these same substitutions over the relevant prompts and mark unused physical tests “deferred”; you do not need to reprint.</div>
<p>The older mentor PDF’s four-rotation timetable and original supply list are reference material. This two-group agenda is the plan for Thursday. If printing is unavailable, use the same prompts digitally or on labeled plain paper; do not add a second set of worksheets.</p></section>
<section class="section compact" id="review"><h2>Review proposals and leave a clear next action.</h2>
<p><strong>11:45–12:42:</strong> require three distinct ideas before selection. Wearables keep an individual future vision, front/back shirt sketch, circuit/battery placement, hat sketch, removable electronics plan, A/B/off effects, and first test question. Robotics pairs show user/need, physical concept, input, two outputs, a decision storyboard, roles, and first test question.</p>
<p><strong>1:16–2:21:</strong> Jennifer uses about three minutes per Wearables student across the review/pitch period; Stephanie uses about five minutes per Robotics pair. Students awaiting review complete diagrams, compare ideas, and prepare their explanation. Tri resolves technical questions.</p>
<p>Record Approved, Revise and Return, or Needs Technical Review. A concept can receive provisional approval with the missing physical test named; keep technical feasibility pending until that test passes. No evidence box should imply work that did not happen. Each Wearables student explains her own contribution to shared practice.</p>
<div class="guide-card"><h3>Deferred-work record</h3><p>Jennifer: retain the paper symbol and arrange wood stitching when those materials are available. Tri + Jennifer: prepare the complete NeoPixel system and arrange a hands-on check before the October 19 design submission if possible. If it remains unavailable, keep the dependency visible in the mentor decision. Stephanie + Tri: record any untested sensor or motion requirement and assign the next equipment check. Keep all follow-up in scheduled school time.</p><p class="record-lines">Project / missing test ____________________ · Owner ____________________<br>Next school-time check / decision ____________________</p></div>
<p><strong>2:21–2:41:</strong> save code and evidence, check readability/uploads, record any pending upload and storage location, power off, count needles and electronics, separate failed kits, and label all project storage. No homework. No major shirt, hat, or robot construction today.</p>
<p><a href="september-24-backup.html#evidence">Student evidence checklist</a> · <a href="mentor-print-center.html#september-24">Print Center</a> · <a href="mentors.html#september-24">Mentor hub</a></p></section>'''
    for name, title, body in [(STUDENT, 'September 24 · Code, test, and design', student), (MENTOR, 'September 24 backup mentor plan', mentor)]:
        (root / name).write_text(page(document, name, title, body), encoding='utf-8', newline='\n')
